// MIT

// WARNING: This file has automatically been generated on Sun, 15 Dec 2019 21:22:54 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "roc/receiver.h"
#include "roc/sender.h"
#include "roc/log.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// roc_log_handler_9e4bbc5e is a proxy for callback roc_log_handler.
void roc_log_handler_9e4bbc5e(roc_log_level level, char* component, char* message);

