// MIT

// WARNING: This file has automatically been generated on Sun, 15 Dec 2019 21:22:54 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void roc_log_handler_9e4bbc5e(roc_log_level level, char* component, char* message) {
	logHandler9E4BBC5E(level, component, message);
}

