// WARNING: This file has automatically been generated on Sun, 03 Nov 2019 20:29:42 CET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "../include/roc/address.h"
#include "../include/roc/config.h"
#include "../include/roc/context.h"
#include "../include/roc/frame.h"
#include "../include/roc/log.h"
#include "../include/roc/platform.h"
#include "../include/roc/receiver.h"
#include "../include/roc/sender.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// roc_log_handler_9e4bbc5e is a proxy for callback roc_log_handler.
void roc_log_handler_9e4bbc5e(roc_log_level level, char* component, char* message);

