// Code generated by generate_enums script from roc-toolkit; DO NOT EDIT!

package roc

// Channel set.
//
//go:generate stringer -type ChannelSet -trimprefix ChannelSet -output channel_set_string.go
type ChannelSet int

const (
	// Stereo.
	//
	// Two channels: left and right.
	ChannelSetStereo ChannelSet = 0x3
)
