// Code generated by "stringer -type ChannelSet -trimprefix ChannelSet -output channel_set_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelSetStereo-3]
}

const _ChannelSet_name = "Stereo"

var _ChannelSet_index = [...]uint8{0, 6}

func (i ChannelSet) String() string {
	i -= 3
	if i < 0 || i >= ChannelSet(len(_ChannelSet_index)-1) {
		return "ChannelSet(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _ChannelSet_name[_ChannelSet_index[i]:_ChannelSet_index[i+1]]
}
