// Code generated by "stringer -type ChannelLayout -trimprefix ChannelLayout -output channel_layout_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ChannelLayoutMultitrack-1]
	_ = x[ChannelLayoutMono-2]
	_ = x[ChannelLayoutStereo-3]
}

const _ChannelLayout_name = "MultitrackMonoStereo"

var _ChannelLayout_index = [...]uint8{0, 10, 14, 20}

func (i ChannelLayout) String() string {
	i -= 1
	if i < 0 || i >= ChannelLayout(len(_ChannelLayout_index)-1) {
		return "ChannelLayout(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ChannelLayout_name[_ChannelLayout_index[i]:_ChannelLayout_index[i+1]]
}
