// Code generated by "stringer -type ClockSyncBackend -trimprefix ClockSyncBackend -output clock_sync_backend_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClockSyncBackendDisable - -1]
	_ = x[ClockSyncBackendDefault-0]
	_ = x[ClockSyncBackendNiq-2]
}

const (
	_ClockSyncBackend_name_0 = "DisableDefault"
	_ClockSyncBackend_name_1 = "Niq"
)

var (
	_ClockSyncBackend_index_0 = [...]uint8{0, 7, 14}
)

func (i ClockSyncBackend) String() string {
	switch {
	case -1 <= i && i <= 0:
		i -= -1
		return _ClockSyncBackend_name_0[_ClockSyncBackend_index_0[i]:_ClockSyncBackend_index_0[i+1]]
	case i == 2:
		return _ClockSyncBackend_name_1
	default:
		return "ClockSyncBackend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
