// MIT

// WARNING: This file has automatically been generated on Sun, 15 Dec 2019 21:22:54 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package roc provides Go bindings for libroc
*/
package roc
