// Code generated by generate_bindings.py script from roc-streaming/bindgen
// roc-toolkit git tag: v0.4.0, commit: 62401be9

package roc

// Forward Error Correction encoding.
//
// Each FEC encoding is compatible with specific protocols.
//
//go:generate stringer -type FecEncoding -trimprefix FecEncoding -output fec_encoding_string.go
type FecEncoding int

const (
	// No FEC encoding.
	//
	// Compatible with ProtoRtp protocol.
	//
	// Pros:
	//  - compatible with third-party software that does not support FECFRAME
	//
	// Cons:
	//  - no packet recovery
	FecEncodingDisable FecEncoding = -1

	// Default FEC encoding.
	//
	// Current default is FecEncodingRs8m.
	FecEncodingDefault FecEncoding = 0

	// Reed-Solomon FEC encoding (RFC 6865) with m=8.
	//
	// Good for small block sizes (below 256 packets). Compatible with
	// ProtoRtpRs8mSource and ProtoRs8mRepair protocols for source and repair
	// endpoints.
	//
	// Pros:
	//  - good repair capabilities even on small block sizes
	//
	// Cons:
	//  - high CPU usage on large block sizes
	FecEncodingRs8m FecEncoding = 1

	// LDPC-Staircase FEC encoding (RFC 6816).
	//
	// Good for large block sizes (above 1024 packets). Compatible with
	// ProtoRtpLdpcSource and ProtoLdpcRepair protocols for source and repair
	// endpoints.
	//
	// Pros:
	//  - low CPU usage even on large block sizes
	//
	// Cons:
	//  - low repair capabilities on small block sizes
	FecEncodingLdpcStaircase FecEncoding = 2
)
