// Code generated by "stringer -type LatencyTunerProfile -trimprefix LatencyTunerProfile -output latency_tuner_profile_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LatencyTunerProfileDefault-0]
	_ = x[LatencyTunerProfileIntact-1]
	_ = x[LatencyTunerProfileResponsive-2]
	_ = x[LatencyTunerProfileGradual-3]
}

const _LatencyTunerProfile_name = "DefaultIntactResponsiveGradual"

var _LatencyTunerProfile_index = [...]uint8{0, 7, 13, 23, 30}

func (i LatencyTunerProfile) String() string {
	if i < 0 || i >= LatencyTunerProfile(len(_LatencyTunerProfile_index)-1) {
		return "LatencyTunerProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LatencyTunerProfile_name[_LatencyTunerProfile_index[i]:_LatencyTunerProfile_index[i+1]]
}
