// Code generated by "stringer -type LatencyTunerBackend -trimprefix LatencyTunerBackend -output latency_tuner_backend_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LatencyTunerBackendDefault-0]
	_ = x[LatencyTunerBackendNiq-2]
}

const (
	_LatencyTunerBackend_name_0 = "Default"
	_LatencyTunerBackend_name_1 = "Niq"
)

func (i LatencyTunerBackend) String() string {
	switch {
	case i == 0:
		return _LatencyTunerBackend_name_0
	case i == 2:
		return _LatencyTunerBackend_name_1
	default:
		return "LatencyTunerBackend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
