// Code generated by "stringer -type LogLevel -trimprefix Log"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LogNone-0]
	_ = x[LogError-1]
	_ = x[LogInfo-2]
	_ = x[LogDebug-3]
	_ = x[LogTrace-4]
}

const _LogLevel_name = "NoneErrorInfoDebugTrace"

var _LogLevel_index = [...]uint8{0, 4, 9, 13, 18, 23}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
