// Code generated by "stringer -type PacketEncoding -trimprefix PacketEncoding"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketEncodingAvpL16-2]
}

const _PacketEncoding_name = "AvpL16"

var _PacketEncoding_index = [...]uint8{0, 6}

func (i PacketEncoding) String() string {
	i -= 2
	if i < 0 || i >= PacketEncoding(len(_PacketEncoding_index)-1) {
		return "PacketEncoding(" + strconv.FormatInt(int64(i+2), 10) + ")"
	}
	return _PacketEncoding_name[_PacketEncoding_index[i]:_PacketEncoding_index[i+1]]
}
