// Code generated by "stringer -type ResamplerProfile -trimprefix ResamplerProfile -output resampler_profile_string.go"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResamplerProfileDefault-0]
	_ = x[ResamplerProfileHigh-1]
	_ = x[ResamplerProfileMedium-2]
	_ = x[ResamplerProfileLow-3]
}

const _ResamplerProfile_name = "DefaultHighMediumLow"

var _ResamplerProfile_index = [...]uint8{0, 7, 11, 17, 20}

func (i ResamplerProfile) String() string {
	if i < 0 || i >= ResamplerProfile(len(_ResamplerProfile_index)-1) {
		return "ResamplerProfile(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResamplerProfile_name[_ResamplerProfile_index[i]:_ResamplerProfile_index[i+1]]
}
