// Code generated by "stringer -type ResamplerProfile -trimprefix ResamplerProfile"; DO NOT EDIT.

package roc

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ResamplerProfileDisable - -1]
	_ = x[ResamplerProfileDefault-0]
	_ = x[ResamplerProfileHigh-1]
	_ = x[ResamplerProfileMedium-2]
	_ = x[ResamplerProfileLow-3]
}

const _ResamplerProfile_name = "DisableDefaultHighMediumLow"

var _ResamplerProfile_index = [...]uint8{0, 7, 14, 18, 24, 27}

func (i ResamplerProfile) String() string {
	i -= -1
	if i < 0 || i >= ResamplerProfile(len(_ResamplerProfile_index)-1) {
		return "ResamplerProfile(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _ResamplerProfile_name[_ResamplerProfile_index[i]:_ResamplerProfile_index[i+1]]
}
