// DO NOT EDIT! Code generated by generate_enums script from roc-toolkit
// roc-toolkit git tag: v0.2.6, commit: 3cbb3d13

package roc

// Resampler profile.
//
// Affects speed and quality. Each resampler backend treats profile in its own
// way.
//
//go:generate stringer -type ResamplerProfile -trimprefix ResamplerProfile -output resampler_profile_string.go
type ResamplerProfile int

const (
	// Do not perform resampling.
	//
	// Clock drift compensation will be disabled in this case. If in doubt, do not
	// disable resampling.
	ResamplerProfileDisable ResamplerProfile = -1

	// Default profile.
	//
	// Current default is ResamplerProfileMedium.
	ResamplerProfileDefault ResamplerProfile = 0

	// High quality, low speed.
	ResamplerProfileHigh ResamplerProfile = 1

	// Medium quality, medium speed.
	ResamplerProfileMedium ResamplerProfile = 2

	// Low quality, high speed.
	ResamplerProfileLow ResamplerProfile = 3
)
