// MIT

// WARNING: This file has automatically been generated on Sun, 15 Dec 2019 21:22:54 MSK.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package roc

/*
#cgo LDFLAGS: -lroc
#include "roc/receiver.h"
#include "roc/sender.h"
#include "roc/log.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
