linters:
  enable:
    - govet
    - revive
    - staticcheck
    - exhaustruct
    - lll
    - misspell
    - dupword
  disable:
    - gosimple
    - unused

linters-settings:
  exhaustruct:
    include:
      - 'roc_.*'
  lll:
    line-length: 100

issues:
  exclude-rules:
    - text: '_ is missing'
      linters:
        - exhaustruct
    - text: 'if-return'
      linters:
        - revive
    - text: 'unused-parameter'
      linters:
        - revive
    - text: 'long'
      linters:
        - dupword
