linters:
  enable:
    - govet
    - revive
    - staticcheck
    - exportloopref
    - lll
    - misspell
    - dupword
  disable:
    - gosimple
    - unused

linters-settings:
  lll:
    line-length: 100
